"use client";

import type { SessionSummary } from "@/lib/utils";

function generateExportText(summary: SessionSummary): string {
  const cs = summary.clinical_summary;
  const lines: string[] = [
    "═══════════════════════════════════════",
    "  MEDINTERPRET — SESSION SUMMARY",
    "═══════════════════════════════════════",
    "",
    `Session ID:    ${summary.session_id}`,
    `Duration:      ${Math.floor(summary.duration_seconds / 60)}m ${Math.floor(summary.duration_seconds % 60)}s`,
    `Languages:     ${summary.source_lang} → ${summary.target_lang}`,
    `Exchanges:     ${summary.exchange_count}`,
    `Mode:          ${summary.mode}`,
    "",
    "─── CLINICAL SUMMARY ───",
    "",
  ];

  if (cs.chief_complaint.length) {
    lines.push(`Chief Complaint: ${cs.chief_complaint.join(", ")}`);
  }
  if (cs.symptoms.length) {
    lines.push(`Symptoms: ${cs.symptoms.join(", ")}`);
  }
  if (cs.conditions.length) {
    lines.push(`Conditions: ${cs.conditions.join(", ")}`);
  }
  if (cs.medications.length) {
    lines.push(`Medications: ${cs.medications.join(", ")}`);
  }
  if (cs.allergies.length) {
    lines.push(`⚠️ Allergies: ${cs.allergies.join(", ")}`);
  }
  if (cs.vitals.length) {
    lines.push(`Vitals: ${cs.vitals.join(", ")}`);
  }
  if (cs.onset_duration.length) {
    lines.push(`Onset/Duration: ${cs.onset_duration.join(", ")}`);
  }
  if (cs.severity.length) {
    lines.push(`Severity: ${cs.severity.join(", ")}`);
  }

  if (summary.flags.length) {
    lines.push("", "─── FLAGS & WARNINGS ───", "");
    summary.flags.forEach((f) => lines.push(`⚠️ ${f}`));
  }

  lines.push(
    "",
    "─── PRIVACY NOTICE ───",
    "",
    "No audio was stored. No transcripts were persisted.",
    "No patient data left this device.",
    "Session data has been purged.",
    "",
    "Generated by MedInterpret on NVIDIA DGX Spark GB10",
    "═══════════════════════════════════════",
  );

  return lines.join("\n");
}

export function ExportButton({ summary }: { summary: SessionSummary }) {
  const handleExport = () => {
    const text = generateExportText(summary);
    navigator.clipboard.writeText(text).then(() => {
      alert("Summary copied to clipboard — paste into EMR");
    }).catch(() => {
      // Fallback: download as text file
      const blob = new Blob([text], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `medinterpret-${summary.session_id}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    });
  };

  return (
    <button
      onClick={handleExport}
      className="touch-target w-full px-6 py-4 bg-primary text-white text-lg font-semibold rounded-xl hover:bg-blue-800 transition-colors"
    >
      📋 Export for EMR
    </button>
  );
}
